version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'case_tecnico_alura_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootPassword'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - database:/var/lib/mysql

volumes:
  database: